# Generated by Django 3.2.8 on 2021-10-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobnumber', models.IntegerField(verbose_name='Job Number')),
                ('refnumber', models.IntegerField(verbose_name='Reference Number')),
                ('rdate', models.DateTimeField(verbose_name='Receiving Date')),
                ('company', models.CharField(max_length=120, verbose_name='Company')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('weight', models.IntegerField(verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=120, verbose_name='Last Name')),
                ('company', models.CharField(max_length=120, verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
