# Generated by Django 3.2.8 on 2021-11-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='jobnumber',
            field=models.IntegerField(verbose_name='Job Number'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='rdate',
            field=models.DateField(verbose_name='Receiving Date'),
        ),
    ]
