# Generated by Django 3.2.8 on 2021-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_activity_rdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='jobnumber',
            field=models.CharField(max_length=120, verbose_name='Job Number'),
        ),
    ]
